tickers_url: 'https://www.sec.gov/files/company_tickers.json'
cik_filler: 13
meta_url: 'https://data.sec.gov/submissions/'
base_filing_url: 'https://www.sec.gov/Archives/edgar/data/'
meta_url_extension: '.json'
Accept-Encoding:
  - gzip
  - deflate
tick_to_cik_headers:
  'User-Agent': 'paul paul.soh.zh.contact@gmail.com'
  'Host': 'www.sec.gov'
sec_meta_headers:
  'User-Agent': 'paul paul.soh.zh.contact@gmail.com'